### ISSUE TITLE
connectionName is ignored

### ISSUE THREAD

**Issue by Arnaud-Dev-Nodejs** [nestjs/mongoose#1166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```typescript
import {
  getConnectionToken,
  MongooseModule,
  MongooseModuleOptions,
} from '@nestjs/mongoose';

import { ConfigModule, ConfigService } from '@mantra/config';
import { LoggerService } from '@mantra/logger';

import { MongooseConfig } from './dto';

export function buildFactoryParams(
  configName: string,
  logger: LoggerService,
  config: ConfigService,
): MongooseModuleOptions {
  logger.debug('buildFactoryParams()');

  const { user, password, hosts, database, options } =
    config.get<MongooseConfig>(configName);

  const uri = `mongodb://${user}:${password}@${hosts}/${database}`;

  const params = {
    uri,
    ...options,
    connectionName: configName,
    connectionFactory: (connection, name) => {
      logger.debug('name:', name); // DatabaseConnection ?!!?
      return connection;
    },
  };

  logger.trace({ params });

  return params;
}

export function MongooseBuilder(configName: string) {
  return MongooseModule.forRootAsync({
    imports: [ConfigModule],
    inject: [LoggerService, ConfigService],
    useFactory: buildFactoryParams.bind(this, configName),
  });
}

```

I try to build multiple connection with a specific connectionName for each based on the Configuration name.

But the connection ignore the connectionName and I get this error with the model after: 
```
0|csmr-tracks  | [Nest] 377  - 12/21/2021, 11:57:18 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the AccountService (LoggerService, DatabaseConnection, ?). Please make sure that the argument MongooseConnectionName at index [2] is available in the AccountModule context.
0|csmr-tracks  | Potential solutions:
0|csmr-tracks  | - If MongooseConnectionName is a provider, is it part of the current AccountModule?
0|csmr-tracks  | - If MongooseConnectionName is exported from a separate @Module, is that module imported within AccountModule?
0|csmr-tracks  |   @Module({
0|csmr-tracks  |     imports: [ /* the Module containing MongooseConnectionName */ ]
0|csmr-tracks  |   })
0|csmr-tracks  | 
0|csmr-tracks  | Error: Nest can't resolve dependencies of the AccountService (LoggerService, DatabaseConnection, ?). Please make sure that the argument MongooseConnectionName at index [2] is available in the AccountModule context.
0|csmr-tracks  | Potential solutions:
0|csmr-tracks  | - If MongooseConnectionName is a provider, is it part of the current AccountModule?
0|csmr-tracks  | - If MongooseConnectionName is exported from a separate @Module, is that module imported within AccountModule?
0|csmr-tracks  |   @Module({
0|csmr-tracks  |     imports: [ /* the Module containing MongooseConnectionName */ ]
0|csmr-tracks  |   })
0|csmr-tracks  |     at Injector.lookupComponentInParentModules (/var/www/app/node_modules/@nestjs/core/injector/injector.js:201:19)
0|csmr-tracks  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
0|csmr-tracks  |     at Injector.resolveComponentInstance (/var/www/app/node_modules/@nestjs/core/injector/injector.js:156:33)
0|csmr-tracks  |     at resolveParam (/var/www/app/node_modules/@nestjs/core/injector/injector.js:108:38)
0|csmr-tracks  |     at async Promise.all (index 2)
0|csmr-tracks  |     at Injector.resolveConstructorParams (/var/www/app/node_modules/@nestjs/core/injector/injector.js:123:27)
0|csmr-tracks  |     at Injector.loadInstance (/var/www/app/node_modules/@nestjs/core/injector/injector.js:52:9)
0|csmr-tracks  |     at Injector.loadProvider (/var/www/app/node_modules/@nestjs/core/injector/injector.js:74:9)
0|csmr-tracks  |     at async Promise.all (index 3)
0|csmr-tracks  |     at InstanceLoader.createInstancesOfProviders (/var/www/app/node_modules/@nestjs/core/injector/instance-loader.js:44:9)



```

### Minimum reproduction code

none

### Steps to reproduce

Just add connectionName to a Mongoose init.

### Expected behavior

Connection should contain the "name + Connection" value as a name.

### Package version

9.0.0

### mongoose version

6.0.8

### NestJS version

8.0.8

### Node.js version

14.16

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by Arnaud-Dev-Nodejs** [comment]
Here is a prefilled example : https://codesandbox.io/s/late-grass-t8y9z

**Comment by jmcdo29** [comment]
![image](https://user-images.githubusercontent.com/28268680/147126602-a7e2f9de-ef68-459a-bf75-13c1bc058a14.png)

Your reproduction fails. Please provide a minimum reproduction repository, as I have already asked. A git repo we can clone and work with locally, with docker-compose to run mongo, is what we're looking for here. I'll reopen the issue when what we've asked for has been provided

**Comment by Arnaud-Dev-Nodejs** [comment]
I found the bug !! 

the connectionName has to be defined in module but not in options :: 
```
export function MongooseBuilder(configName: string) {
  return MongooseModule.forRootAsync({
   connectionName: configName
    imports: [ConfigModule],
    inject: [LoggerService, ConfigService],
    useFactory: buildFactoryParams,
  });
}
```
Strange, never documented but its worked fine.

**Comment by fetahokey** [comment]
still facing "the argument DatabaseConnection at index [0] is available in the MongooseModule context" with the ^above
