### ISSUE TITLE
Nest can't resolve dependencies of the Test1Model (?). Please make sure that the argument connection1Connection

### ISSUE THREAD

**Issue by tangb** [nestjs/mongoose#1200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using multiple mongoose connections, unit tests always fail due to missing reference to connection.
I tryed a lot of thing including using mongo-memory-server but it always failed.

I encountered this problem on nestjs v7.0.0 but I'm also reproducing this on latest version 8.3.0 available on example posted on my github repo. The repo includes a full nestjs project with a single unit test that fails with following output:

```
 FAIL  src/test/test.service.test.ts
  TestService
    createTest1
      ✕ should create test (11 ms)

  ● TestService › createTest1 › should create test

    Nest can't resolve dependencies of the Test2Model (?). Please make sure that the argument connection2Connection at index [0] is available in the MongooseModule context.

    Potential solutions:
    - If connection2Connection is a provider, is it part of the current MongooseModule?
    - If connection2Connection is exported from a separate @Module, is that module imported within MongooseModule?
      @Module({
        imports: [ /* the Module containing connection2Connection */ ]
      })

      at TestingInjector.lookupComponentInParentModules (node_modules/@nestjs/core/injector/injector.js:202:19)
      at TestingInjector.resolveComponentInstance (node_modules/@nestjs/core/injector/injector.js:157:33)
      at TestingInjector.resolveComponentInstance (node_modules/@nestjs/testing/testing-injector.js:16:45)
      at resolveParam (node_modules/@nestjs/core/injector/injector.js:108:38)
          at async Promise.all (index 0)
      at TestingInjector.resolveConstructorParams (node_modules/@nestjs/core/injector/injector.js:123:27)
      at TestingInjector.loadInstance (node_modules/@nestjs/core/injector/injector.js:52:9)
      at TestingInjector.loadProvider (node_modules/@nestjs/core/injector/injector.js:74:9)
          at async Promise.all (index 3)
      at TestingInstanceLoader.createInstancesOfProviders (node_modules/@nestjs/core/injector/instance-loader.js:44:9)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        3.882 s, estimated 5 s
```

### Minimum reproduction code

https://github.com/tangb/nestjs-mongoose-testing

### Steps to reproduce

* clone repo from reproduction code url
* npm install
* npm run test

### Expected behavior

Run test correctly with multiple mongoose connection ;-)

### Package version

9.0.2

### mongoose version

6.1.6

### NestJS version

8.2.5

### Node.js version

12.22.6

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
This isn't a bug, but badly written test code. Unit tests should refrain from using `imports` and just use `providers` to have better control over the dependencies. You should also be providing a mock for __all__ injected dependencies in a class, you only provide a mock for `Test1Model` in your code. [For a lot of general NestJS testing examples, you can reference this repo](https://github.com/jmcdo29/testing-nestjs). For more help, please [visit our Discord](https://discord.gg/nestjs)
