### ISSUE TITLE
Issue with RXJS dependency (0 , rxjs_1.lastValueFrom) is not a function

### ISSUE THREAD

**Issue by ursnj** [nestjs/mongoose#1784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

App is crashing even with latest nestjs versions, with bellow error

[Nest] 911  - 05/04/2023, 7:51:24 AM   ERROR [ExceptionHandler] (0 , rxjs_1.lastValueFrom) is not a function
TypeError: (0 , rxjs_1.lastValueFrom) is not a function
    at Function.<anonymous> (/Users/nj/Desktop/projects/riosh/probe/node_modules/@nestjs/mongoose/dist/mongoose-core.module.js:61:55)
    at Generator.next (<anonymous>)
    at /Users/nj/Desktop/projects/riosh/probe/node_modules/@nestjs/mongoose/dist/mongoose-core.module.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/nj/Desktop/projects/riosh/probe/node_modules/@nestjs/mongoose/dist/mongoose-core.module.js:16:12)
    at InstanceWrapper.useFactory [as metatype] (/Users/nj/Desktop/projects/riosh/probe/node_modules/@nestjs/mongoose/dist/mongoose-core.module.js:60:31)
    at Injector.instantiateClass (/Users/nj/Desktop/projects/riosh/probe/packages/api/node_modules/@nestjs/core/injector/injector.js:354:55)
    at callback (/Users/nj/Desktop/projects/riosh/probe/packages/api/node_modules/@nestjs/core/injector/injector.js:56:45)
    at Injector.resolveConstructorParams (/Users/nj/Desktop/projects/riosh/probe/packages/api/node_modules/@nestjs/core/injector/injector.js:136:24)
    at Injector.loadInstance (/Users/nj/Desktop/projects/riosh/probe/packages/api/node_modules/@nestjs/core/injector/injector.js:61:13)

Packages used:

"@nestjs/common": "^9.2.1",
    "@nestjs/core": "^9.2.1",
    "@nestjs/jwt": "^10.0.1",
    "@nestjs/mongoose": "^9.2.2",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.2.1",
    "@nestjs/platform-socket.io": "^9.4.0",
    "@nestjs/websockets": "^9.4.0",
    "bcrypt": "^5.1.0",
    "class-validator": "^0.14.0",
    "lodash": "^4.17.21",
    "mongoose": "^6.8.0",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.8.1",
    "uuid": "^8.3.2"

### Minimum reproduction code

NA

### Steps to reproduce

1. npm i
2. npm start

### Expected behavior

Application should start with out any errors.

### Package version

9.2.2

### mongoose version

6.8.0

### NestJS version

9.2.1

### Node.js version

16.19.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

NA

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
