### ISSUE TITLE
Nest.js crashes on mongoose schema validation failure

### ISSUE THREAD

**Issue by knopkem** [nestjs/mongoose#973]
I'm submitting a bug report.
I followed the tutorial https://docs.nestjs.com/techniques/mongodb closely and everything works so far.
Trying schema validation using the required property works but it crashes the application (no matter if I put try, catch around the call to save new data, and normally with nest.js this is not needed).

## Current behavior
Nest.js crashes on validation error

## Expected behavior
Nest.js catches the exception and can send a response

## Minimal reproduction of the problem with instructions
no repo yet, but could create one

## What is the motivation / use case for changing the behavior?
while I could do validation before inserting the data, it would be nice to protect the database via schema validation.

## Environment

<pre>
"@nestjs/common": "^8.0.5",
"@nestjs/core": "^8.0.5",
"@nestjs/mongoose": "^8.0.0",
"mongoose": "^5.13.5",
</pre>

- Node v16.4.2
- Platform:  Windows 10

## Callstack

<code>

[...]\node_modules\mongoose\lib\document.js:2760
    this.$__.validationError = new ValidationError(this);
                               ^
ValidationError: Log validation failed: level: Path `level` is required.
    at model.Document.invalidate ([...]\node_modules\mongoose\lib\document.js:2760:32)
    at [...]\node_modules\mongoose\lib\document.js:2552:17
    at [...]\node_modules\mongoose\lib\schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
</code>

**Comment by knopkem** [comment]
I just realized that this was a lack of understanding of exceptions in async functions on my side, rather than a bug, sorry. closing
